In [21]:
import cv2
import numpy as np 
import pandas as pd
from matplotlib import pyplot
import imutils
from imutils.perspective import four_point_transform
from skimage.filters import threshold_local
import argparse


In [22]:
image = cv2.imread(r"C:\Users\ASUS\Downloads\pss.jpeg")
cv2.imshow("image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(image)


[[[182 171 209]
  [180 169 207]
  [177 166 206]
  ...
  [ 54  43 113]
  [ 55  44 114]
  [ 55  44 114]]

 [[181 170 208]
  [179 168 206]
  [176 165 205]
  ...
  [ 53  42 112]
  [ 54  43 113]
  [ 54  43 113]]

 [[178 167 207]
  [175 164 204]
  [172 160 202]
  ...
  [ 52  41 111]
  [ 53  42 112]
  [ 54  43 113]]

 ...

 [[ 85 111 111]
  [ 88 114 114]
  [ 92 118 118]
  ...
  [ 41  36  75]
  [ 40  36  72]
  [ 40  36  72]]

 [[ 84 110 110]
  [ 87 113 113]
  [ 90 116 116]
  ...
  [ 39  34  73]
  [ 40  36  72]
  [ 40  36  72]]

 [[ 83 109 109]
  [ 86 112 112]
  [ 90 116 116]
  ...
  [ 38  33  72]
  [ 40  36  72]
  [ 41  37  73]]]


In [23]:
orig = image.copy()
ratio = image.shape[0]/500.0
image = imutils.resize(image, height =500)
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
gray = cv2.GaussianBlur(gray, (5,5),0)
cv2.imshow("gray",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
edges = cv2.Canny(gray, 75, 200)
cv2.imshow("edges",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
cnts = cv2.findContours(edges,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
cnts = sorted(cnts,key = cv2.contourArea, reverse = True)[:5]

In [26]:
for c in cnts:
    p = cv2.arcLength(c,True)
    approx = cv2.approxPolyDP(c,0.02*p,True)
    if len(approx)==4:
        screenCnt = approx
        break
    

In [27]:
cv2.drawContours(image, [screenCnt], -1,  (0,255,0), 2)
cv2.imshow("outline",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 

In [28]:
warped = four_point_transform(orig, screenCnt.reshape(4, 2) * ratio)
warped = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
t = threshold_local(warped, 11, offset = 10, method = "gaussian")
warped =  (warped > t).astype("uint8") * 255

In [ ]:

cv2.imshow("original", imutils.resize(orig, height = 550))
cv2.imshow("scanned", imutils.resize(warped, height = 550))
cv2.waitKey(0)
cv2.destroyAllWindows()